apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grpc-client-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /hello
            backend:
              serviceName: grpc-client-k8s
              servicePort: 8080

