apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grps-client-ingress
  namespace: quarkus-apero-code
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /grpc-client
            pathType: Prefix
            backend:
              service:
                name: grps-client-k8s
                port:
                  number: 4000

