INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, BEER_PRODUCER, BEER_COUNTRY, BEER_PRICE) VALUES (NEXTVAL('hibernate_sequence'), 'Chouffe', 'yellow', '', '', 0);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, BEER_PRODUCER, BEER_COUNTRY, BEER_PRICE) VALUES (NEXTVAL('hibernate_sequence'), 'Chimay', 'amber', '', '', 0);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, BEER_PRODUCER, BEER_COUNTRY, BEER_PRICE) VALUES (NEXTVAL('hibernate_sequence'), 'Kwack', 'amber', '', '', 0);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, BEER_PRODUCER, BEER_COUNTRY, BEER_PRICE) VALUES (NEXTVAL('hibernate_sequence'), 'Ch''ti Triple','yellow', '', '', 0);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, BEER_PRODUCER, BEER_COUNTRY, BEER_PRICE) VALUES (NEXTVAL('hibernate_sequence'), 'Goudale', 'amber', '', '', 0);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, BEER_PRODUCER, BEER_COUNTRY, BEER_PRICE) VALUES (NEXTVAL('hibernate_sequence'), 'Karmeliete', 'yellow', '', '', 0);