apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: k8s-quickstart-gateway
  namespace: quarkus-apero-code
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
       - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-quickstart-vs
  namespace: quarkus-apero-code
spec:
  hosts:
    - '*'
  gateways:
    - k8s-quickstart-gateway
  http:
    - route:
        - destination:
            host: kubernetes-quickstart
            port:
              number: 2000